### PR TITLE
Updated flag icons to Twemoji

### PR DESCRIPTION
**Pull request by Karojen**

### CODE REVIEW

**Comment by TheRhysWyrill** [comment]
Are these icons confirmed to display correctly when in the Game List?

**Comment by Karojen** [comment]
> Are these icons confirmed to display correctly when in the Game List?

Tested it in dev mode. Yes, these icons display as they should.

**Comment by Karojen** [comment]
> Are these icons confirmed to display correctly when in the Game List?

At first they were stretched, but after editing the size they display correctly now.

**Comment by Karojen** [comment]
> Are these icons confirmed to display correctly when in the Game List?

At first they were stretched, but after editing the size they display correctly now.

**Comment by TheRhysWyrill** [comment]
Hi, sorry about this but I just tested the new flags and they appear to still be slightly distorted as you can see here:

New Flag:
Screenshot_2022-09-01_20-23-43

Old Flag:
Screenshot_2022-09-01_20-25-08

**Comment by TheRhysWyrill** [comment]
Looks good to me, thanks, merged, though will alter the flag size to be just slightly larger.

**Pull request merged**
